### ISSUE TITLE
AccessOrType  

### ISSUE THREAD

**Issue by mahugnon** [moosetechnology/PowerBuilderParser#24]
access OrType should parse `this. post`

**Comment by mahugnon** [comment]
Try to fix it. Too many broken tests for a slight reason.
Here si my fix:
`variable
	<rename: #arrayWithSize into: #arrayDefinition>
	^ this optional , blank optional , identifier , $% parser optional
		, $( parser not , arrayWithSize optional`

**Comment by Larcheveque** [comment]
Are you sure it's not interference with the modification you did on the Preprocessor? Is it accepted in powerbuilder?

**Comment by madisontechnology** [comment]
It's might be possible. I will check the original  source and compare

**Comment by mahugnon** [comment]
It might be possible. I will check the original source and compare

**Comment by mahugnon** [comment]
It is not the preprocessor. Here is the proof
```PowerBuilder
//contrôle des dates de signature et de réception
		if ib_tst_deb or ib_tst_sig or ib_tst_rec then //fiche 28231 $Alain.k$ 14/12/2007
			//ib_tst_sig_rec = false //fiche 28231 $Alain.k$ 14/12/2007
			if f_ctrl_sig_rec(ld_dat_sig,ld_dat_rec,ld_prt_deb,false) >=1 then 
				if this.getColumnName() = "dat_rec" then
					this.post setitem(1,"dat_rec","0000-00-00")
					this.post accepttext()
					this. post setcolumn("dat_rec")
```
